<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>captioner</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Captioner.Core/Captioner.Core.csproj" />
    <ProjectReference Include="../Captioner.Engine/Captioner.Engine.csproj" />
    <ProjectReference Include="../Captioner.Infrastructure/Captioner.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="System.CommandLine" Version="2.0.0" />
  </ItemGroup>
</Project>
